[package]
name = "imagine"
version = "0.1.0"
authors = ["Cole Lawrence <colelawr@gmail.com>"]
edition = "2018"

[dependencies]
generational-arena = "0.1"
serde_json = "1.0"

[dependencies.arrayvec]
version = "0.4"
features = ["serde-1"]
